### ISSUE TITLE
Errors running tsc with clutz output

### ISSUE THREAD

**Issue by jjudd** [angular/clutz#295]
I've got clutz hooked up to our build system and generating definition files. Caveat: I am using the ability to specify closure entry points that I introduced in #294.

The definition files I generate have some duplicates and seem to be missing quite a few symbols. Not sure if I'm doing something wrong or if this is Clutz doing something wonky.

For example, XHR_Instance is duplicated.

```typescript
declare namespace ಠ_ಠ.clutz.ng.compiler {
  class XHR extends XHR_Instance {
  }
  class XHR_Instance {
    private noStructuralTyping_: any;
  }
}
declare namespace ಠ_ಠ.clutz.ng.compiler {
  class XHR extends XHR_Instance {
  }
  class XHR_Instance {
    private noStructuralTyping_: any;
  }
}
```

```
Error at app/webroot/ts/app/clutz-definitions/support.d.ts:18135:9: Duplicate identifier 'XHR'.
Error at app/webroot/ts/app/clutz-definitions/support.d.ts:18137:9: Duplicate identifier 'XHR_Instance'.
```

PrivateType is missing.

```typescript
declare namespace ಠ_ಠ.clutz.node.http {
  var ClientRequest : ಠ_ಠ.clutz.PrivateType;
}
```

```
Error at app/webroot/ts/app/clutz-definitions/support.d.ts:18584:33: Module 'ಠ_ಠ.clutz' has no exported member 'PrivateType'.
```

Several other symbols also seem to be missing: ChromeEvent, GlobalEvent, GlobalError, ChromeStringArrayEvent, etc.

```
Error at app/webroot/ts/app/clutz-definitions/support.d.ts:13554:18: Cannot find name 'ChromeEvent'.
```

I am able to reproduce the issue, using an empty js file and the closure-compiler externs located at https://github.com/google/closure-compiler/tree/master/externs. 

When I run the TypeScript compiler using the output, I get.
```
Error at app/webroot/ts/app/clutz-definitions/foo.d.ts:469:20: Cannot find name 'GlobalEvent'.
```

The clutz command is 
```makefile
JS_CLOSURE_EXTERNS := $(shell find app/webroot/js/closure/closure-externs/ -type f -name '*.js')
clutz/build/install/clutz/bin/clutz $(foreach extern, $(JS_CLOSURE_EXTERNS), --externs $(extern)) \
		-o app/webroot/ts/app/clutz-definitions/foo.d.ts foo.js
```

When I try to use `--emitPlatformExterns` to see if that would include the missing symbols, I get a null pointer exception

```java
java.lang.NullPointerException
	at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.visitObjectType(DeclarationGenerator.java:1671)
	at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.visitClassOrInterface(DeclarationGenerator.java:1181)
	at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.walk(DeclarationGenerator.java:1014)
	at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.access$200(DeclarationGenerator.java:962)
	at com.google.javascript.clutz.DeclarationGenerator.declareNamespace(DeclarationGenerator.java:656)
	at com.google.javascript.clutz.DeclarationGenerator.processExternSymbols(DeclarationGenerator.java:581)
	at com.google.javascript.clutz.DeclarationGenerator.produceDts(DeclarationGenerator.java:377)
	at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:287)
	at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:267)
	at com.google.javascript.clutz.DeclarationGenerator.main(DeclarationGenerator.java:140)
```

I'll create a repo that reproduces the issue and link it here.

**Comment by rkirov** [comment]
The documentation is incomplete, clutz output always needs 'closure.lib.d.ts'. You can find that file in the resources dir. That would take care of `PrivateType`, `GlobalEvent` and `GlobalError`.

The missing symbols ChromeEvent and ChromeStringArrayEvent should probably be added to https://github.com/angular/clutz/blob/ac92bfe6c8edf9516d21c30f34330e15ce13750f/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L84 . Not sure how we missed them in the unit tests. Maybe we are using different versions of Closure?

Finally, duplicated indentifiers and NPE sound like true bugs, and we should investigate further. Feel free to open separate bugs for those.

**Comment by rkirov** [comment]
Actually, the doc does say 

> When compiling TypeScript code that depends on the closure code, include the src/resources/closure.lib.d.ts along with out.d.ts.

If this was confusing, please contribute a better wording.

**Comment by jjudd** [comment]
Thanks for that. I didn't read closely enough :). I'll make a PR that makes that a bit more obvious for those, like me, who do not read a closely as they should.

I'll investigate the other issues I ran into and log bugs for them when I have a bit more info.

**Comment by rkirov** [comment]
@jjudd any update on this issue? It is a bit too broad to be useful for other users and I would like to close it, once all the smaller bugs are extracted into subissues.

**Comment by jjudd** [comment]
@rkirov I'll close it. @lambertjamesd is working on splitting up this issue into smaller bugs and fixing those.
